#+TITLE: eng: British-American English converter (CLI)

Eng is a CLI tool to translate from American to British English and vice versa.
*with a preference for the [[https://en.wikipedia.org/wiki/Oxford_spellinhttps://en.wikipedia.org/wiki/Oxford_spellingg][Oxford English Dictionary spelling]]**

* FORK - Rationale
Why did I fork this? As u/moononthebones put it so succinctly on [[https://www.reddit.com/r/Python/comments/xlzyi1/eng_translate_british_english_into_american/][reddit]]:

#+BEGIN_QUOTE
*u/moononthebones*
A lot of these American spellings are also valid British English spellings: Oxford spelling style (preferred by most scientific publications) uses ‘-ize’ endings, so ‘acclimatize’ is a correct British variant. Whereas British English will always use ‘analyse’ rather than ‘analyze’.
#+END_QUOTE

My guiding principle when communicating is to use language that is clear, accurate and avoids ambiguity where possible. Lofty Cambridge spellings are unnecessary, when Oxford -ize spellings are also valid British English words, but importantly readers of both dialects can understand them.

Cambridge spellings might be interesting and make a statement about one's British English identity, but they are not clear and cause confusion to international audiences.

This fork, when translating American to British English, prefers the [[https://en.wikipedia.org/wiki/Oxford_spelling][Oxford Spelling always]].

- *TODO (Maybe) Add an option to choose between Oxford and Cambridge spelling styles, so that -ize translates to -ise*
Is this really worth bothering to do? If you want the Cambridge spelling, put on your tweed hat, zip up your red trousers and say a small prayer to Nigel Farage and the King, and then use the [[https://www.reddit.com/r/Python/comments/xlzyi1/eng_translate_british_english_into_american/][original project this was forked from]].

Oh, and I also changed the readme from Markdown (yuk) to orgmode (yay).

** Setup/Install

*** Create a virtual environment and install the dependencies.
#+BEGIN_SRC sh
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
#+END_SRC

*** Running the CLI
Where =-v= / =--verbose= will enumerate the changes and output them to STDERR

#+BEGIN_SRC sh
$ echo center of the faucet | python -m eng --target uk --verbose
Replacing 'faucet' with 'tap'
Replacing 'center' with 'centre'
centre of the tap
#+END_SRC

I have changed the CLI class to only accept input via STDIN and output to STDOUT (verbose output to STDERR). The original of this fork would overwrite the input file without warning, which is a nope for me.

To convert files, use the shell's built-in redirection:

#+BEGIN_SRC sh
$ python -m eng --target us -v < tests/british-story.txt > tests/british-story-translated.txt
Replacing 'tranquillity' with 'tranquility'
Replacing 'pyjamas' with 'pajamas'
Replacing 'cosy' with 'cozy'
Replacing 'realised' with 'realized'
Replacing 'neighbours' with 'neighbors'
Replacing 'cosiness' with 'coziness'
Replacing 'moulded' with 'molded'
Replacing 'favourite' with 'favorite'
Replacing 'signalled' with 'signaled'
Replacing 'colour' with 'color'
Replacing 'parlour' with 'parlor'
Replacing 'savoured' with 'savored'
Replacing 'doughnut' with 'donut'
Replacing 'neighbouring' with 'neighboring'
Replacing 'marvelling' with 'marveling'
Replacing 'odour' with 'odor'
Replacing 'tantalising' with 'tantalizing'
Replacing 'postman' with 'mailman'
Replacing 'savouring' with 'savoring'
Replacing 'Grey' with 'Gray'
$ 
#+END_SRC

** Run tests

#+BEGIN_SRC sh
pytest tests/test_fixer.py
#+END_SRC

- TODO needs updating to reflect the changes in the CLI from this for
