#!/usr/bin/env bash

#shellcheck source=../.qfuncs.sh
source ~/.qfuncs.sh

set -e

cat words-OED.txt | while read -r line; do

   line_words=($line)

   if [[ ${line_words[0]} == ${line_words[1]} ]]; then
      echo $line >>words-ize.txt
   else
      echo $line >>words-oed-clean.txt
   fi
done
